"""add phone number

Revision ID: 97aa7310d3e8
Revises: fd2dad7a0685
Create Date: 2021-11-21 09:50:19.339078

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "97aa7310d3e8"
down_revision = "fd2dad7a0685"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("phone_number", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "phone_number")
    # ### end Alembic commands ###
